// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyView is the golang structure of table co_company_view for DAO operations like Where/Data.
type CompanyView struct {
	g.Meta               `orm:"table:co_company_view, do:true"`
	Id                   interface{} //
	Name                 interface{} //
	ContactName          interface{} //
	ContactMobile        interface{} //
	UserId               interface{} //
	State                interface{} //
	Remark               interface{} //
	CreatedBy            interface{} //
	CreatedAt            *gtime.Time //
	UpdatedBy            interface{} //
	UpdatedAt            *gtime.Time //
	DeletedBy            interface{} //
	DeletedAt            *gtime.Time //
	ParentId             interface{} //
	Address              interface{} //
	LicenseId            interface{} //
	LicenseState         interface{} //
	LogoId               interface{} //
	StartLevel           interface{} //
	CountryCode          interface{} //
	Region               interface{} //
	Score                interface{} //
	CommissionRate       interface{} //
	FdAccountId          interface{} //
	FdLimitState         interface{} //
	FdAllowExceed        interface{} //
	FdCurrencyCode       interface{} //
	FdAccountType        interface{} //
	FdPrecisionOfBalance interface{} //
	FdBalance            interface{} //
	FdFrozenAmount       interface{} //
	FdTodayAccountSum    interface{} //
	FdWeekAccountSum     interface{} //
	FdMonthAccountSum    interface{} //
	FdQuarterAccountSum  interface{} //
	FdYearAccountSum     interface{} //
	CompanyType          interface{} //
}
