// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyTeamView is the golang structure of table co_company_team_view for DAO operations like Where/Data.
type CompanyTeamView struct {
	g.Meta            `orm:"table:co_company_team_view, do:true"`
	Id                interface{} //
	Name              interface{} //
	OwnerEmployeeId   interface{} //
	CaptainEmployeeId interface{} //
	UnionMainId       interface{} //
	ParentId          interface{} //
	Remark            interface{} //
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
	DeletedAt         *gtime.Time //
	Type              interface{} //
	Slogan            interface{} //
	Title             interface{} //
	LogoId            interface{} //
	CreatedBy         interface{} //
	CompanyType       interface{} //
}
