// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyEmployeeView is the golang structure of table co_company_employee_view for DAO operations like Where/Data.
type CompanyEmployeeView struct {
	g.Meta               `orm:"table:co_company_employee_view, do:true"`
	Id                   interface{} //
	No                   interface{} //
	Avatar               interface{} //
	Name                 interface{} //
	Mobile               interface{} //
	UnionMainId          interface{} //
	State                interface{} //
	LastActiveIp         interface{} //
	HiredAt              *gtime.Time //
	CreatedBy            interface{} //
	CreatedAt            *gtime.Time //
	UpdatedBy            interface{} //
	UpdatedAt            *gtime.Time //
	DeletedBy            interface{} //
	DeletedAt            *gtime.Time //
	Sex                  interface{} //
	Remark               interface{} //
	CountryCode          interface{} //
	Region               interface{} //
	Email                interface{} //
	WeixinAccount        interface{} //
	Address              interface{} //
	WorkCardAvatar       interface{} //
	CommissionRate       interface{} //
	FdAccountId          interface{} //
	FdLimitState         interface{} //
	FdAllowExceed        interface{} //
	FdCurrencyCode       interface{} //
	FdAccountType        interface{} //
	FdPrecisionOfBalance interface{} //
	FdBalance            interface{} //
	FdFrozenBlance       interface{} //
	FdTodayAccountSum    interface{} //
	FdWeekAccountSum     interface{} //
	FdMonthAccountSum    interface{} //
	FdQuarterAccountSum  interface{} //
	FdYearAccountSum     interface{} //
	CompanyType          interface{} //
}
