// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyTeamMember is the golang structure of table co_company_team_member for DAO operations like Where/Data.
type CompanyTeamMember struct {
	g.Meta       `orm:"table:co_company_team_member, do:true"`
	Id           interface{} // ID
	TeamId       interface{} // 团队ID
	EmployeeId   interface{} // 成员ID
	InviteUserId interface{} // 邀约人ID
	UnionMainId  interface{} // 关联主体ID
	JoinAt       *gtime.Time // 加入时间
}
