// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccountBillsView is the golang structure of table co_fd_account_bills_view for DAO operations like Where/Data.
type FdAccountBillsView struct {
	g.Meta        `orm:"table:co_fd_account_bills_view, do:true"`
	Id            interface{} //
	FromUserId    interface{} //
	ToUserId      interface{} //
	FdAccountId   interface{} //
	BeforeBalance interface{} //
	Amount        interface{} //
	AfterBalance  interface{} //
	UnionOrderId  interface{} //
	UnionMainId   interface{} //
	InOutType     interface{} //
	TradeType     interface{} //
	TradeAt       *gtime.Time //
	Remark        interface{} //
	TradeState    interface{} //
	HandlingFee   interface{} //
	ExtJson       interface{} //
	DeletedAt     *gtime.Time //
	DeletedBy     interface{} //
	CreatedAt     *gtime.Time //
	CreatedBy     interface{} //
	CompanyType   interface{} //
}
