// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccountView is the golang structure of table co_fd_account_view for DAO operations like Where/Data.
type FdAccountView struct {
	g.Meta             `orm:"table:co_fd_account_view, do:true"`
	Id                 interface{} //
	Name               interface{} //
	UnionLicenseId     interface{} //
	UnionUserId        interface{} //
	CurrencyCode       interface{} //
	IsEnabled          interface{} //
	LimitState         interface{} //
	PrecisionOfBalance interface{} //
	Balance            interface{} //
	Version            interface{} //
	CreatedAt          *gtime.Time //
	CreatedBy          interface{} //
	UpdatedAt          *gtime.Time //
	UpdatedBy          interface{} //
	DeletedAt          *gtime.Time //
	DeletedBy          interface{} //
	SceneType          interface{} //
	AccountType        interface{} //
	AccountNumber      interface{} //
	UnionMainId        interface{} //
	AllowExceed        interface{} //
	FrozenAmount       interface{} //
	TodayAccountSum    interface{} //
	WeekAccountSum     interface{} //
	MonthAccountSum    interface{} //
	QuarterAccountSum  interface{} //
	YearAccountSum     interface{} //
	CompanyType        interface{} //
}
