// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FdAccountBill is the golang structure of table co_fd_account_bill for DAO operations like Where/Data.
type FdAccountBill struct {
	g.Meta `orm:"table:co_fd_account_bill, do:true"`
}
