// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccountDetailView is the golang structure of table co_fd_account_detail_view for DAO operations like Where/Data.
type FdAccountDetailView struct {
	g.Meta            `orm:"table:co_fd_account_detail_view, do:true"`
	Id                interface{} //
	TodayAccountSum   interface{} //
	TodayUpdatedAt    *gtime.Time //
	WeekAccountSum    interface{} //
	WeekUpdatedAt     *gtime.Time //
	MonthAccountSum   interface{} //
	MonthUpdatedAt    *gtime.Time //
	QuarterAccountSum interface{} //
	QuarterUpdatedAt  *gtime.Time //
	YearAccountSum    interface{} //
	YearUpdatedAt     *gtime.Time //
	UnionMainId       interface{} //
	SysUserId         interface{} //
	Version           interface{} //
	SceneType         interface{} //
	CompanyType       interface{} //
}
