// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdBankCard is the golang structure of table co_fd_bank_card for DAO operations like Where/Data.
type FdBankCard struct {
	g.Meta        `orm:"table:co_fd_bank_card, do:true"`
	Id            interface{} // ID
	BankName      interface{} // 银行名称
	CardType      interface{} // 银行卡类型：1借记卡，2储蓄卡
	CardNumber    interface{} // 银行卡号
	ExpiredAt     *gtime.Time // 有效期
	HolderName    interface{} // 银行卡开户名
	BankOfAccount interface{} // 开户行
	State         interface{} // 状态：0禁用，1正常
	Remark        interface{} // 备注信息
	UserId        interface{} // 用户id，表示属于谁
	CreatedAt     *gtime.Time //
	CreatedBy     interface{} //
	UpdatedAt     *gtime.Time //
	UpdatedBy     interface{} //
	DeletedAt     *gtime.Time //
	DeletedBy     interface{} //
}
