// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FdCurrencyView is the golang structure of table co_fd_currency_view for DAO operations like Where/Data.
type FdCurrencyView struct {
	g.Meta `orm:"table:co_fd_currency_view, do:true"`
}
