// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FdCurrency is the golang structure of table co_fd_currency for DAO operations like Where/Data.
type FdCurrency struct {
	g.Meta        `orm:"table:co_fd_currency, do:true"`
	Code          interface{} // 国家编码
	EnName        interface{} // 国家英文名称
	CnName        interface{} // 国家中文名称
	CurrencyCode  interface{} // 货币编码
	CurrencyCn    interface{} // 货币中文名称
	CurrencyEn    interface{} // 货币英文名称
	Symbol        interface{} // 货币符号
	SymbolNative  interface{} // 货币原生符号
	IsLegalTender interface{} // 是否法定货币：1是，0否
	CurrencyRate  interface{} // 货币汇率，本币为人民币
}
