// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoiceDetailView is the golang structure of table co_fd_invoice_detail_view for DAO operations like Where/Data.
type FdInvoiceDetailView struct {
	g.Meta        `orm:"table:co_fd_invoice_detail_view, do:true"`
	Id            interface{} //
	TaxNumber     interface{} //
	TaxName       interface{} //
	BillIds       interface{} //
	Amount        interface{} //
	Rate          interface{} //
	RateMount     interface{} //
	Remark        interface{} //
	Type          interface{} //
	State         interface{} //
	AuditUserIds  interface{} //
	MakeType      interface{} //
	MakeUserId    interface{} //
	MakeAt        *gtime.Time //
	CourierName   interface{} //
	CourierNumber interface{} //
	FdInvoiceId   interface{} //
	AuditUserId   interface{} //
	AuditReplyMsg interface{} //
	AuditAt       *gtime.Time //
	UserId        interface{} //
	UnionMainId   interface{} //
	Email         interface{} //
	CreatedAt     *gtime.Time //
	CreatedBy     interface{} //
	UpdatedAt     *gtime.Time //
	UpdatedBy     interface{} //
	DeletedAt     *gtime.Time //
	DeletedBy     interface{} //
	BelongTo      interface{} //
	CompanyType   interface{} //
}
