// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoiceView is the golang structure of table co_fd_invoice_view for DAO operations like Where/Data.
type FdInvoiceView struct {
	g.Meta        `orm:"table:co_fd_invoice_view, do:true"`
	Id            interface{} //
	Name          interface{} //
	TaxId         interface{} //
	Addr          interface{} //
	Email         interface{} //
	UserId        interface{} //
	AuditUserId   interface{} //
	AuditReplyMsg interface{} //
	AuditAt       *gtime.Time //
	State         interface{} //
	UnionMainId   interface{} //
	CreatedAt     *gtime.Time //
	CreatedBy     interface{} //
	UpdatedAt     *gtime.Time //
	UpdatedBy     interface{} //
	DeletedAt     *gtime.Time //
	DeletedBy     interface{} //
	CompanyType   interface{} //
}
