// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdRecharge is the golang structure of table co_fd_recharge for DAO operations like Where/Data.
type FdRecharge struct {
	g.Meta         `orm:"table:co_fd_recharge, do:true"`
	Id             interface{} //
	UserId         interface{} // 用户ID
	CurrencyCode   interface{} // 币种
	Amount         interface{} // 金额
	RechargeMethod interface{} // 方式：1手动冲正、2银行卡、3支付宝、4微信、5云闪付、6翼支付
	RechargeTime   *gtime.Time // 充值时间
	Status         interface{} // 状态:0待处理、1已完成、2已取消、4失败
	PaymentOrderId interface{} // 外部支付订单，即一般为第三方支付平台生成的订单号
	BillsId        interface{} // 交易流水号，一般用于后续的队长和查询
	AuditState     interface{} // 审核状态：0待审核，1通过、2不通过
	Remark         interface{} // 备注
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
	DeletedAt      *gtime.Time //
}
