// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdRechargeView is the golang structure of table co_fd_recharge_view for DAO operations like Where/Data.
type FdRechargeView struct {
	g.Meta            `orm:"table:co_fd_recharge_view, do:true"`
	Id                interface{} //
	UserId            interface{} //
	Username          interface{} //
	CurrencyCode      interface{} //
	Amount            interface{} //
	RechargeMethod    interface{} //
	PaymentAt         *gtime.Time //
	PaymentOrderNo    interface{} //
	TransactionNo     interface{} //
	State             interface{} //
	AuditState        interface{} //
	AuditReply        interface{} //
	IpAddress         interface{} //
	UserAgent         interface{} //
	UnionMainId       interface{} //
	AccountId         interface{} //
	Remark            interface{} //
	ScreenshotId      interface{} //
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
	DeletedAt         *gtime.Time //
	AccountNumber     interface{} //
	AccountName       interface{} //
	AccountEnabled    interface{} //
	AccountLimitState interface{} //
	AuditId           interface{} //
	CompanyType       interface{} //
}
