// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"{TplImportPrefix}/internal"
)

type {TplTableNameCamelCase}Dao = internal.{TplTableNameCamelCase}Dao

var (
	// {TplTableNameCamelCase} is globally public accessible object for table {TplTableName} operations.
	{TplTableNameCamelCase} = func(module co_interface.IModules) IDao[internal.{TplTableNameCamelCase}Columns] {
        return NewDao[internal.{TplTableNameCamelCase}Columns](module.GetConfig(), internal.New{TplTableNameCamelCase}Dao())
    }
)
