// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-company-modules/co_interface"
	"github.com/SupenBysz/gf-admin-company-modules/co_model/co_dao/internal"
)

type CompanyTeamDao = internal.CompanyTeamDao

var (
	// CompanyTeam is globally public accessible object for table pro_company_team operations.
	CompanyTeam = func(module co_interface.IModules) IDao[internal.CompanyTeamColumns] {
		return NewDao[internal.CompanyTeamColumns](module.GetConfig(), internal.NewCompanyTeamDao())
	}
)
