// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-company-modules/co_interface"
	"github.com/SupenBysz/gf-admin-company-modules/co_model/co_dao/internal"
	"github.com/SupenBysz/gf-admin-company-modules/utility/dao_helper"
)

type internalCompanyTeamMemberDao = *dao_helper.CustomDao[internal.CompanyTeamMemberColumns]

// CompanyTeamMemberDao 是 pro_company_team_member 表的数据访问对象。
// 您可以在其上定义自定义方法，以根据需要扩展其功能。
type companyTeamMemberDao struct {
	internalCompanyTeamMemberDao
}

var (
	// CompanyTeamMember 表 pro_company_team_member 操作的全局公共可访问对象。
	CompanyTeamMember = func(module co_interface.IModules) *companyTeamMemberDao {
		return &companyTeamMemberDao{
			internalCompanyTeamMemberDao: &dao_helper.CustomDao[internal.CompanyTeamMemberColumns]{
				IDao: internal.NewCompanyTeamMemberDao(),
			},
		}
	}
)
