// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-company-modules/co_interface"
	"github.com/SupenBysz/gf-admin-company-modules/co_model/co_dao/internal"
)

type CompanyEmployeeDao = internal.CompanyEmployeeDao

var (
	// CompanyEmployee is globally public accessible object for table pro_company_employee operations.
	CompanyEmployee = func(module co_interface.IModules) IDao[internal.CompanyEmployeeColumns] {
		return NewDao[internal.CompanyEmployeeColumns](module.GetConfig(), internal.NewCompanyEmployeeDao())
	}
)
