// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-community/utility/daoctl/dao_interface"
	"github.com/SupenBysz/gf-admin-company-modules/co_model/co_dao/internal"
)

type FdCurrency = dao_interface.TIDao[internal.FdCurrencyColumns]

func NewFdCurrency(dao ...dao_interface.IDao) FdCurrency {
	return (FdCurrency)(internal.NewFdCurrencyDao(dao...))
}
