// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-community/utility/daoctl/dao_interface"
	"github.com/SupenBysz/gf-admin-company-modules/co_model/co_dao/internal"
)

type FdInvoiceDetail = dao_interface.TIDao[internal.FdInvoiceDetailColumns]

func NewFdInvoiceDetail(dao ...dao_interface.IDao) FdInvoiceDetail {
	return (FdInvoiceDetail)(internal.NewFdInvoiceDetailDao(dao...))
}
