// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-company-modules/co_model/co_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type FdRechargeDao = dao_interface.TIDao[internal.FdRechargeColumns]

func NewFdRecharge(dao ...dao_interface.IDao) FdRechargeDao {
	return (FdRechargeDao)(internal.NewFdRechargeDao(dao...))
}

var (
	FdRecharge = NewFdRecharge()
)
