
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name:     "gf-admin-pro"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link: "pgsql:user=user password=password host=127.0.0.1 port=5432 dbname=dnName sslmode=disable"
        tables: "co_company,co_company_employee,co_company_team,co_company_team_member, 
        co_fd_account, co_fd_account_bill, co_fd_bank_card, co_fd_currency, co_fd_invoice, co_fd_invoice_detail, co_fd_account_detail"
        removePrefix: "co_"
        descriptionTag:  true
        noModelComment:  true
        withTime: false
        # - link: "pgsql:user=kysion password=kysiondb host=182.43.195.225 port=15432 dbname=gf-admin sslmode=disable"
