// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyTeamMemberView is the golang structure for table company_team_member_view.
type CompanyTeamMemberView struct {
	Id           int64       `json:"id"           orm:"id"             description:""`
	TeamId       int64       `json:"teamId"       orm:"team_id"        description:""`
	EmployeeId   int64       `json:"employeeId"   orm:"employee_id"    description:""`
	InviteUserId int64       `json:"inviteUserId" orm:"invite_user_id" description:""`
	UnionMainId  int64       `json:"unionMainId"  orm:"union_main_id"  description:""`
	JoinAt       *gtime.Time `json:"joinAt"       orm:"join_at"        description:""`
	CompanyType  int         `json:"companyType"  orm:"company_type"   description:""`
}
