// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyEmployeeView is the golang structure for table company_employee_view.
type CompanyEmployeeView struct {
	Id                   int64       `json:"id"                   orm:"id"                      description:""`
	No                   string      `json:"no"                   orm:"no"                      description:""`
	Avatar               string      `json:"avatar"               orm:"avatar"                  description:""`
	Name                 string      `json:"name"                 orm:"name"                    description:""`
	Mobile               string      `json:"mobile"               orm:"mobile"                  description:""`
	UnionMainId          int64       `json:"unionMainId"          orm:"union_main_id"           description:""`
	State                int         `json:"state"                orm:"state"                   description:""`
	LastActiveIp         string      `json:"lastActiveIp"         orm:"last_active_ip"          description:""`
	HiredAt              *gtime.Time `json:"hiredAt"              orm:"hired_at"                description:""`
	CreatedBy            int64       `json:"createdBy"            orm:"created_by"              description:""`
	CreatedAt            *gtime.Time `json:"createdAt"            orm:"created_at"              description:""`
	UpdatedBy            int64       `json:"updatedBy"            orm:"updated_by"              description:""`
	UpdatedAt            *gtime.Time `json:"updatedAt"            orm:"updated_at"              description:""`
	DeletedBy            int64       `json:"deletedBy"            orm:"deleted_by"              description:""`
	DeletedAt            *gtime.Time `json:"deletedAt"            orm:"deleted_at"              description:""`
	Sex                  int         `json:"sex"                  orm:"sex"                     description:""`
	Remark               string      `json:"remark"               orm:"remark"                  description:""`
	CountryCode          string      `json:"countryCode"          orm:"country_code"            description:""`
	Region               string      `json:"region"               orm:"region"                  description:""`
	Email                string      `json:"email"                orm:"email"                   description:""`
	WeixinAccount        string      `json:"weixinAccount"        orm:"weixin_account"          description:""`
	Address              string      `json:"address"              orm:"address"                 description:""`
	WorkCardAvatar       string      `json:"workCardAvatar"       orm:"work_card_avatar"        description:""`
	CommissionRate       int         `json:"commissionRate"       orm:"commission_rate"         description:""`
	FdAccountId          int64       `json:"fdAccountId"          orm:"fd_account_id"           description:""`
	FdLimitState         int         `json:"fdLimitState"         orm:"fd_limit_state"          description:""`
	FdAllowExceed        int         `json:"fdAllowExceed"        orm:"fd_allow_exceed"         description:""`
	FdCurrencyCode       string      `json:"fdCurrencyCode"       orm:"fd_currency_code"        description:""`
	FdAccountType        int         `json:"fdAccountType"        orm:"fd_account_type"         description:""`
	FdPrecisionOfBalance int         `json:"fdPrecisionOfBalance" orm:"fd_precision_of_balance" description:""`
	FdBalance            int64       `json:"fdBalance"            orm:"fd_balance"              description:""`
	FdFrozenAmount       int64       `json:"fdFrozenAmount"       orm:"fd_frozen_amount"        description:""`
	FdTodayAccountSum    int         `json:"fdTodayAccountSum"    orm:"fd_today_account_sum"    description:""`
	FdWeekAccountSum     int         `json:"fdWeekAccountSum"     orm:"fd_week_account_sum"     description:""`
	FdMonthAccountSum    int         `json:"fdMonthAccountSum"    orm:"fd_month_account_sum"    description:""`
	FdQuarterAccountSum  int         `json:"fdQuarterAccountSum"  orm:"fd_quarter_account_sum"  description:""`
	FdYearAccountSum     int64       `json:"fdYearAccountSum"     orm:"fd_year_account_sum"     description:""`
	CompanyType          int         `json:"companyType"          orm:"company_type"            description:""`
}
