// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyTeamView is the golang structure for table company_team_view.
type CompanyTeamView struct {
	Id                int64       `json:"id"                orm:"id"                  description:""`
	Name              string      `json:"name"              orm:"name"                description:""`
	OwnerEmployeeId   int64       `json:"ownerEmployeeId"   orm:"owner_employee_id"   description:""`
	CaptainEmployeeId int64       `json:"captainEmployeeId" orm:"captain_employee_id" description:""`
	UnionMainId       int64       `json:"unionMainId"       orm:"union_main_id"       description:""`
	ParentId          int64       `json:"parentId"          orm:"parent_id"           description:""`
	Remark            string      `json:"remark"            orm:"remark"              description:""`
	CreatedAt         *gtime.Time `json:"createdAt"         orm:"created_at"          description:""`
	UpdatedAt         *gtime.Time `json:"updatedAt"         orm:"updated_at"          description:""`
	DeletedAt         *gtime.Time `json:"deletedAt"         orm:"deleted_at"          description:""`
	Type              int         `json:"type"              orm:"type"                description:""`
	Slogan            string      `json:"slogan"            orm:"slogan"              description:""`
	Title             string      `json:"title"             orm:"title"               description:""`
	LogoId            int64       `json:"logoId"            orm:"logo_id"             description:""`
	CreatedBy         int64       `json:"createdBy"         orm:"created_by"          description:""`
	CompanyType       int         `json:"companyType"       orm:"company_type"        description:""`
}
