// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyEmployeeView is the golang structure for table company_employee_view.
type CompanyEmployeeView struct {
	Id             int64       `json:"id"             orm:"id"               description:""`
	No             string      `json:"no"             orm:"no"               description:""`
	Avatar         string      `json:"avatar"         orm:"avatar"           description:""`
	Name           string      `json:"name"           orm:"name"             description:""`
	Mobile         string      `json:"mobile"         orm:"mobile"           description:""`
	UnionMainId    int64       `json:"unionMainId"    orm:"union_main_id"    description:""`
	State          int         `json:"state"          orm:"state"            description:""`
	LastActiveIp   string      `json:"lastActiveIp"   orm:"last_active_ip"   description:""`
	HiredAt        *gtime.Time `json:"hiredAt"        orm:"hired_at"         description:""`
	CreatedBy      int64       `json:"createdBy"      orm:"created_by"       description:""`
	CreatedAt      *gtime.Time `json:"createdAt"      orm:"created_at"       description:""`
	UpdatedBy      int64       `json:"updatedBy"      orm:"updated_by"       description:""`
	UpdatedAt      *gtime.Time `json:"updatedAt"      orm:"updated_at"       description:""`
	DeletedBy      int64       `json:"deletedBy"      orm:"deleted_by"       description:""`
	DeletedAt      *gtime.Time `json:"deletedAt"      orm:"deleted_at"       description:""`
	Sex            int         `json:"sex"            orm:"sex"              description:""`
	Remark         string      `json:"remark"         orm:"remark"           description:""`
	CountryCode    string      `json:"countryCode"    orm:"country_code"     description:""`
	Region         string      `json:"region"         orm:"region"           description:""`
	Email          string      `json:"email"          orm:"email"            description:""`
	WeixinAccount  string      `json:"weixinAccount"  orm:"weixin_account"   description:""`
	Address        string      `json:"address"        orm:"address"          description:""`
	WorkCardAvatar string      `json:"workCardAvatar" orm:"work_card_avatar" description:""`
	CommissionRate int         `json:"commissionRate" orm:"commission_rate"  description:""`
	CompanyType    int         `json:"companyType"    orm:"company_type"     description:""`
}
