// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccountBillsView is the golang structure for table fd_account_bills_view.
type FdAccountBillsView struct {
	Id            int64       `json:"id"            orm:"id"             description:""`
	FromUserId    int64       `json:"fromUserId"    orm:"from_user_id"   description:""`
	ToUserId      int64       `json:"toUserId"      orm:"to_user_id"     description:""`
	FdAccountId   int64       `json:"fdAccountId"   orm:"fd_account_id"  description:""`
	BeforeBalance int64       `json:"beforeBalance" orm:"before_balance" description:""`
	Amount        int64       `json:"amount"        orm:"amount"         description:""`
	AfterBalance  int64       `json:"afterBalance"  orm:"after_balance"  description:""`
	UnionOrderId  int64       `json:"unionOrderId"  orm:"union_order_id" description:""`
	UnionMainId   int64       `json:"unionMainId"   orm:"union_main_id"  description:""`
	InOutType     int         `json:"inOutType"     orm:"in_out_type"    description:""`
	TradeType     int         `json:"tradeType"     orm:"trade_type"     description:""`
	TradeAt       *gtime.Time `json:"tradeAt"       orm:"trade_at"       description:""`
	Remark        string      `json:"remark"        orm:"remark"         description:""`
	TradeState    int         `json:"tradeState"    orm:"trade_state"    description:""`
	HandlingFee   int64       `json:"handlingFee"   orm:"handling_fee"   description:""`
	ExtJson       string      `json:"extJson"       orm:"ext_json"       description:""`
	DeletedAt     *gtime.Time `json:"deletedAt"     orm:"deleted_at"     description:""`
	DeletedBy     int64       `json:"deletedBy"     orm:"deleted_by"     description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     orm:"created_at"     description:""`
	CreatedBy     int64       `json:"createdBy"     orm:"created_by"     description:""`
	CompanyType   int         `json:"companyType"   orm:"company_type"   description:""`
}
