// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

// FdAccountBill is the golang structure for table fd_account_bill.
type FdAccountBill struct {
}
