// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccountDetailView is the golang structure for table fd_account_detail_view.
type FdAccountDetailView struct {
	Id                int64       `json:"id"                orm:"id"                  description:""`
	TodayAccountSum   int         `json:"todayAccountSum"   orm:"today_account_sum"   description:""`
	TodayUpdatedAt    *gtime.Time `json:"todayUpdatedAt"    orm:"today_updated_at"    description:""`
	WeekAccountSum    int         `json:"weekAccountSum"    orm:"week_account_sum"    description:""`
	WeekUpdatedAt     *gtime.Time `json:"weekUpdatedAt"     orm:"week_updated_at"     description:""`
	MonthAccountSum   int         `json:"monthAccountSum"   orm:"month_account_sum"   description:""`
	MonthUpdatedAt    *gtime.Time `json:"monthUpdatedAt"    orm:"month_updated_at"    description:""`
	QuarterAccountSum int         `json:"quarterAccountSum" orm:"quarter_account_sum" description:""`
	QuarterUpdatedAt  *gtime.Time `json:"quarterUpdatedAt"  orm:"quarter_updated_at"  description:""`
	YearAccountSum    int64       `json:"yearAccountSum"    orm:"year_account_sum"    description:""`
	YearUpdatedAt     *gtime.Time `json:"yearUpdatedAt"     orm:"year_updated_at"     description:""`
	UnionMainId       int64       `json:"unionMainId"       orm:"union_main_id"       description:""`
	SysUserId         int64       `json:"sysUserId"         orm:"sys_user_id"         description:""`
	Version           int         `json:"version"           orm:"version"             description:""`
	SceneType         int         `json:"sceneType"         orm:"scene_type"          description:""`
	CompanyType       int         `json:"companyType"       orm:"company_type"        description:""`
}
