// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

// FdAccountBillView is the golang structure for table fd_account_bill_view.
type FdAccountBillView struct {
}
