// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccountView is the golang structure for table fd_account_view.
type FdAccountView struct {
	Id                 int64       `json:"id"                 orm:"id"                   description:""`
	Name               string      `json:"name"               orm:"name"                 description:""`
	UnionLicenseId     int64       `json:"unionLicenseId"     orm:"union_license_id"     description:""`
	UnionUserId        int64       `json:"unionUserId"        orm:"union_user_id"        description:""`
	CurrencyCode       string      `json:"currencyCode"       orm:"currency_code"        description:""`
	IsEnabled          int         `json:"isEnabled"          orm:"is_enabled"           description:""`
	LimitState         int         `json:"limitState"         orm:"limit_state"          description:""`
	PrecisionOfBalance int         `json:"precisionOfBalance" orm:"precision_of_balance" description:""`
	Balance            int64       `json:"balance"            orm:"balance"              description:""`
	Version            int         `json:"version"            orm:"version"              description:""`
	CreatedAt          *gtime.Time `json:"createdAt"          orm:"created_at"           description:""`
	CreatedBy          int64       `json:"createdBy"          orm:"created_by"           description:""`
	UpdatedAt          *gtime.Time `json:"updatedAt"          orm:"updated_at"           description:""`
	UpdatedBy          int64       `json:"updatedBy"          orm:"updated_by"           description:""`
	DeletedAt          *gtime.Time `json:"deletedAt"          orm:"deleted_at"           description:""`
	DeletedBy          int64       `json:"deletedBy"          orm:"deleted_by"           description:""`
	SceneType          int         `json:"sceneType"          orm:"scene_type"           description:""`
	AccountType        int         `json:"accountType"        orm:"account_type"         description:""`
	AccountNumber      string      `json:"accountNumber"      orm:"account_number"       description:""`
	UnionMainId        int64       `json:"unionMainId"        orm:"union_main_id"        description:""`
	AllowExceed        int         `json:"allowExceed"        orm:"allow_exceed"         description:""`
	FrozenBlance       int64       `json:"frozenBlance"       orm:"frozen_blance"        description:""`
	TodayAccountSum    int         `json:"todayAccountSum"    orm:"today_account_sum"    description:""`
	WeekAccountSum     int         `json:"weekAccountSum"     orm:"week_account_sum"     description:""`
	MonthAccountSum    int         `json:"monthAccountSum"    orm:"month_account_sum"    description:""`
	QuarterAccountSum  int         `json:"quarterAccountSum"  orm:"quarter_account_sum"  description:""`
	YearAccountSum     int64       `json:"yearAccountSum"     orm:"year_account_sum"     description:""`
	CompanyType        int         `json:"companyType"        orm:"company_type"         description:""`
}
