// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdBankCardView is the golang structure for table fd_bank_card_view.
type FdBankCardView struct {
	Id            int64       `json:"id"            orm:"id"              description:""`
	BankName      string      `json:"bankName"      orm:"bank_name"       description:""`
	CardType      int         `json:"cardType"      orm:"card_type"       description:""`
	CardNumber    string      `json:"cardNumber"    orm:"card_number"     description:""`
	ExpiredAt     *gtime.Time `json:"expiredAt"     orm:"expired_at"      description:""`
	HolderName    string      `json:"holderName"    orm:"holder_name"     description:""`
	BankOfAccount string      `json:"bankOfAccount" orm:"bank_of_account" description:""`
	State         int         `json:"state"         orm:"state"           description:""`
	Remark        string      `json:"remark"        orm:"remark"          description:""`
	UserId        int64       `json:"userId"        orm:"user_id"         description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     orm:"created_at"      description:""`
	CreatedBy     int64       `json:"createdBy"     orm:"created_by"      description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     orm:"updated_at"      description:""`
	UpdatedBy     int64       `json:"updatedBy"     orm:"updated_by"      description:""`
	DeletedAt     *gtime.Time `json:"deletedAt"     orm:"deleted_at"      description:""`
	DeletedBy     int64       `json:"deletedBy"     orm:"deleted_by"      description:""`
	CompanyType   int         `json:"companyType"   orm:"company_type"    description:""`
}
