// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

// FdCurrencyView is the golang structure for table fd_currency_view.
type FdCurrencyView struct {
}
