// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoiceDetailView is the golang structure for table fd_invoice_detail_view.
type FdInvoiceDetailView struct {
	Id            int64       `json:"id"            orm:"id"              description:""`
	TaxNumber     string      `json:"taxNumber"     orm:"tax_number"      description:""`
	TaxName       string      `json:"taxName"       orm:"tax_name"        description:""`
	BillIds       string      `json:"billIds"       orm:"bill_ids"        description:""`
	Amount        int64       `json:"amount"        orm:"amount"          description:""`
	Rate          int         `json:"rate"          orm:"rate"            description:""`
	RateMount     int64       `json:"rateMount"     orm:"rate_mount"      description:""`
	Remark        string      `json:"remark"        orm:"remark"          description:""`
	Type          int         `json:"type"          orm:"type"            description:""`
	State         int         `json:"state"         orm:"state"           description:""`
	AuditUserIds  int64       `json:"auditUserIds"  orm:"audit_user_ids"  description:""`
	MakeType      int         `json:"makeType"      orm:"make_type"       description:""`
	MakeUserId    int64       `json:"makeUserId"    orm:"make_user_id"    description:""`
	MakeAt        *gtime.Time `json:"makeAt"        orm:"make_at"         description:""`
	CourierName   string      `json:"courierName"   orm:"courier_name"    description:""`
	CourierNumber string      `json:"courierNumber" orm:"courier_number"  description:""`
	FdInvoiceId   int64       `json:"fdInvoiceId"   orm:"fd_invoice_id"   description:""`
	AuditUserId   int64       `json:"auditUserId"   orm:"audit_user_id"   description:""`
	AuditReplyMsg string      `json:"auditReplyMsg" orm:"audit_reply_msg" description:""`
	AuditAt       *gtime.Time `json:"auditAt"       orm:"audit_at"        description:""`
	UserId        int64       `json:"userId"        orm:"user_id"         description:""`
	UnionMainId   int64       `json:"unionMainId"   orm:"union_main_id"   description:""`
	Email         string      `json:"email"         orm:"email"           description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     orm:"created_at"      description:""`
	CreatedBy     int64       `json:"createdBy"     orm:"created_by"      description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     orm:"updated_at"      description:""`
	UpdatedBy     int64       `json:"updatedBy"     orm:"updated_by"      description:""`
	DeletedAt     *gtime.Time `json:"deletedAt"     orm:"deleted_at"      description:""`
	DeletedBy     int64       `json:"deletedBy"     orm:"deleted_by"      description:""`
	BelongTo      int         `json:"belongTo"      orm:"belong_to"       description:""`
	CompanyType   int         `json:"companyType"   orm:"company_type"    description:""`
}
