// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoiceView is the golang structure for table fd_invoice_view.
type FdInvoiceView struct {
	Id            int64       `json:"id"            orm:"id"              description:""`
	Name          string      `json:"name"          orm:"name"            description:""`
	TaxId         string      `json:"taxId"         orm:"tax_id"          description:""`
	Addr          string      `json:"addr"          orm:"addr"            description:""`
	Email         string      `json:"email"         orm:"email"           description:""`
	UserId        int64       `json:"userId"        orm:"user_id"         description:""`
	AuditUserId   int64       `json:"auditUserId"   orm:"audit_user_id"   description:""`
	AuditReplyMsg string      `json:"auditReplyMsg" orm:"audit_reply_msg" description:""`
	AuditAt       *gtime.Time `json:"auditAt"       orm:"audit_at"        description:""`
	State         int         `json:"state"         orm:"state"           description:""`
	UnionMainId   int64       `json:"unionMainId"   orm:"union_main_id"   description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     orm:"created_at"      description:""`
	CreatedBy     int64       `json:"createdBy"     orm:"created_by"      description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     orm:"updated_at"      description:""`
	UpdatedBy     int64       `json:"updatedBy"     orm:"updated_by"      description:""`
	DeletedAt     *gtime.Time `json:"deletedAt"     orm:"deleted_at"      description:""`
	DeletedBy     int64       `json:"deletedBy"     orm:"deleted_by"      description:""`
	CompanyType   int         `json:"companyType"   orm:"company_type"    description:""`
}
