// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdRecharge is the golang structure for table fd_recharge.
type FdRecharge struct {
	Id             int64       `json:"id"             orm:"id"               description:"唯一标识每一条充值记录"`
	UserId         int64       `json:"userId"         orm:"user_id"          description:"用户ID，关联用户表主键，用于标识充值所属用户"`
	Username       string      `json:"username"       orm:"username"         description:"用户账号，冗余存储方便快速查询用户相关充值记录，无需每次都关联用户表"`
	CurrencyCode   string      `json:"currencyCode"   orm:"currency_code"    description:"货币代码，如CNY（人民币）、USD（美元）等"`
	Amount         float64     `json:"amount"         orm:"amount"           description:"充值金额，小数点后保留2位，且金额需大于0"`
	RechargeMethod int         `json:"rechargeMethod" orm:"recharge_method"  description:"充值方式：1 - 银行卡；2 - 支付宝；3 - 微信；4 - 云闪付；5 - ApplePay；6 - PayPal；7 - AmazonPay；8 - 线下现金（若有对应业务）；9 - 区块链钱包；10 - 其他（可进一步在备注说明）"`
	PaymentAt      *gtime.Time `json:"paymentAt"      orm:"payment_at"       description:"充值支付时间，记录用户实际支付成功的时间"`
	PaymentOrderNo string      `json:"paymentOrderNo" orm:"payment_order_no" description:"外部支付订单号，第三方支付平台生成的订单编号"`
	TransactionNo  string      `json:"transactionNo"  orm:"transaction_no"   description:"交易流水号，系统内部生成，用于后续对账和查询"`
	State          int         `json:"state"          orm:"state"            description:"充值状态：0 - 待处理；1 - 处理中；2 - 已支付；3 - 部分成功；4 - 失败；5 - 已取消；6 - 待确认"`
	AuditState     int         `json:"auditState"     orm:"audit_state"      description:"审核状态：0 - 待审核；1 - 审核通过；2 - 审核不通过；3 - 审核中（人工复审）；4 - 补充资料待审核"`
	AuditReply     string      `json:"auditReply"     orm:"audit_reply"      description:"审核意见，审核人员填写审核通过或不通过的原因等"`
	IpAddress      string      `json:"ipAddress"      orm:"ip_address"       description:"用户发起充值请求时的IP地址"`
	UserAgent      string      `json:"userAgent"      orm:"user_agent"       description:"用户使用的设备和浏览器信息"`
	UnionMainId    int64       `json:"unionMainId"    orm:"union_main_id"    description:""`
	AccountId      int64       `json:"accountId"      orm:"account_id"       description:"财务账户"`
	Remark         string      `json:"remark"         orm:"remark"           description:"备注，可记录一些特殊情况或额外信息"`
	ScreenshotId   int64       `json:"screenshotId"   orm:"screenshot_id"    description:"充值截图"`
	CreatedAt      *gtime.Time `json:"createdAt"      orm:"created_at"       description:"记录创建时间，即充值请求提交时间"`
	UpdatedAt      *gtime.Time `json:"updatedAt"      orm:"updated_at"       description:"记录最后更新时间，每次记录状态等信息变更时更新"`
	DeletedAt      *gtime.Time `json:"deletedAt"      orm:"deleted_at"       description:"逻辑删除时间，用于软删除，非真正物理删除，便于数据追溯和恢复"`
}
