// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdRechargeView is the golang structure for table fd_recharge_view.
type FdRechargeView struct {
	Id                int64       `json:"id"                orm:"id"                  description:""`
	UserId            int64       `json:"userId"            orm:"user_id"             description:""`
	Username          string      `json:"username"          orm:"username"            description:""`
	CurrencyCode      string      `json:"currencyCode"      orm:"currency_code"       description:""`
	Amount            float64     `json:"amount"            orm:"amount"              description:""`
	RechargeMethod    int         `json:"rechargeMethod"    orm:"recharge_method"     description:""`
	PaymentAt         *gtime.Time `json:"paymentAt"         orm:"payment_at"          description:""`
	PaymentOrderNo    string      `json:"paymentOrderNo"    orm:"payment_order_no"    description:""`
	TransactionNo     string      `json:"transactionNo"     orm:"transaction_no"      description:""`
	State             int         `json:"state"             orm:"state"               description:""`
	AuditState        int         `json:"auditState"        orm:"audit_state"         description:""`
	AuditReply        string      `json:"auditReply"        orm:"audit_reply"         description:""`
	IpAddress         string      `json:"ipAddress"         orm:"ip_address"          description:""`
	UserAgent         string      `json:"userAgent"         orm:"user_agent"          description:""`
	UnionMainId       int64       `json:"unionMainId"       orm:"union_main_id"       description:""`
	AccountId         int64       `json:"accountId"         orm:"account_id"          description:""`
	Remark            string      `json:"remark"            orm:"remark"              description:""`
	ScreenshotId      int64       `json:"screenshotId"      orm:"screenshot_id"       description:""`
	CreatedAt         *gtime.Time `json:"createdAt"         orm:"created_at"          description:""`
	UpdatedAt         *gtime.Time `json:"updatedAt"         orm:"updated_at"          description:""`
	DeletedAt         *gtime.Time `json:"deletedAt"         orm:"deleted_at"          description:""`
	AccountNumber     string      `json:"accountNumber"     orm:"account_number"      description:""`
	AccountName       string      `json:"accountName"       orm:"account_name"        description:""`
	AccountEnabled    int         `json:"accountEnabled"    orm:"account_enabled"     description:""`
	AccountLimitState int         `json:"accountLimitState" orm:"account_limit_state" description:""`
	AuditId           int64       `json:"auditId"           orm:"audit_id"            description:""`
	CompanyType       int         `json:"companyType"       orm:"company_type"        description:""`
}
