// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdRecharge is the golang structure for table fd_recharge.
type FdRecharge struct {
	Id             int         `json:"id"             orm:"id"               description:""`
	UserId         int64       `json:"userId"         orm:"user_id"          description:"用户ID"`
	CurrencyCode   string      `json:"currencyCode"   orm:"currency_code"    description:"币种"`
	Amount         float64     `json:"amount"         orm:"amount"           description:"金额"`
	RechargeMethod int         `json:"rechargeMethod" orm:"recharge_method"  description:"方式：1手动冲正、2银行卡、3支付宝、4微信、5云闪付、6翼支付"`
	RechargeTime   *gtime.Time `json:"rechargeTime"   orm:"recharge_time"    description:"充值时间"`
	Status         string      `json:"status"         orm:"status"           description:"状态:0待处理、1已完成、2已取消、4失败"`
	PaymentOrderId string      `json:"paymentOrderId" orm:"payment_order_id" description:"外部支付订单，即一般为第三方支付平台生成的订单号"`
	BillsId        string      `json:"billsId"        orm:"bills_id"         description:"交易流水号，一般用于后续的队长和查询"`
	AuditState     int         `json:"auditState"     orm:"audit_state"      description:"审核状态：0待审核，1通过、2不通过"`
	Remark         string      `json:"remark"         orm:"remark"           description:"备注"`
	CreatedAt      *gtime.Time `json:"createdAt"      orm:"created_at"       description:""`
	UpdatedAt      *gtime.Time `json:"updatedAt"      orm:"updated_at"       description:""`
	DeletedAt      *gtime.Time `json:"deletedAt"      orm:"deleted_at"       description:""`
}
