// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"{TplImportPrefix}/internal"
)

type {TplTableNameCamelCase}Dao = internal.{TplTableNameCamelCase}Dao

var (
	// {TplTableNameCamelCase} is globally public accessible object for table {TplTableName} operations.
	{TplTableNameCamelCase} = internal.New{TplTableNameCamelCase}Dao()
)
