// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/SupenBysz/gf-admin-company-modules/internal/logic/co_audit"
	_ "github.com/SupenBysz/gf-admin-company-modules/internal/logic/co_license"
	_ "github.com/SupenBysz/gf-admin-company-modules/internal/logic/company"
	_ "github.com/SupenBysz/gf-admin-company-modules/internal/logic/financial"
)
