// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/SupenBysz/gf-admin-company-modules/co_interface"
	"{TplImportPrefix}/internal"
)

type {TplTableNameCamelCase} = internal.{TplTableNameCamelCase}Dao

func New{TplTableNameCamelCase}(dao ...co_interface.IDao) *{TplTableNameCamelCase} {
	return internal.New{TplTableNameCamelCase}Dao(dao...)
}
