// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AuditDao is the data access object for table co_audit.
type AuditDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns AuditColumns // columns contains all the column names of Table for convenient usage.
}

// AuditColumns defines and stores column names for table co_audit.
type AuditColumns struct {
	Id           string //
	State        string // 审核状态：-1不通过，0待审核，1通过
	Reply        string // 不通过时回复的审核不通过原因
	UnionMainId  string // 关联主体ID
	Category     string // 业务类别
	AuditData    string // 待审核的业务数据包
	ExpireAt     string // 服务时限
	AuditReplyAt string // 审核回复时间
	HistoryItems string // 历史申请记录
	CreatedAt    string //
	AuditUserId  string // 审核操作者id
}

// auditColumns holds the columns for table co_audit.
var auditColumns = AuditColumns{
	Id:           "id",
	State:        "state",
	Reply:        "reply",
	UnionMainId:  "union_main_id",
	Category:     "category",
	AuditData:    "audit_data",
	ExpireAt:     "expire_at",
	AuditReplyAt: "audit_reply_at",
	HistoryItems: "history_Items",
	CreatedAt:    "created_at",
	AuditUserId:  "audit_user_id",
}

// NewAuditDao creates and returns a new DAO object for table data access.
func NewAuditDao(proxy ...dao_interface.IDao) *AuditDao {
	var dao *AuditDao
	if len(proxy) > 0 {
		dao = &AuditDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: auditColumns,
		}
		return dao
	}

	return &AuditDao{
		group:   "default",
		table:   "co_audit",
		columns: auditColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AuditDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AuditDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *AuditDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *AuditDao) Columns() AuditColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AuditDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *AuditDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AuditDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
