// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CompanyTeamDao is the data access object for table co_company_team.
type CompanyTeamDao struct {
	dao_interface.IDao
	table       string             // table is the underlying table name of the DAO.
	group       string             // group is the database configuration group name of current DAO.
	columns     CompanyTeamColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// CompanyTeamColumns defines and stores column names for table co_company_team.
type CompanyTeamColumns struct {
	Id                string // ID
	Name              string // 团队名称，公司维度下唯一
	OwnerEmployeeId   string // 团队所有者/业务总监/业务经理/团队队长
	CaptainEmployeeId string // 团队队长编号/小组组长
	UnionMainId       string // 所属主体单位ID
	ParentId          string // 父级ID
	Remark            string // 备注
	CreatedAt         string //
	UpdatedAt         string //
	DeletedAt         string //
	Type              string // 类型：0部门，1团队，2小组
	Slogan            string // 口号
	Title             string // 称号
	LogoId            string // LOGO
	CreatedBy         string // 创建者
}

// companyTeamColumns holds the columns for table co_company_team.
var companyTeamColumns = CompanyTeamColumns{
	Id:                "id",
	Name:              "name",
	OwnerEmployeeId:   "owner_employee_id",
	CaptainEmployeeId: "captain_employee_id",
	UnionMainId:       "union_main_id",
	ParentId:          "parent_id",
	Remark:            "remark",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
	Type:              "type",
	Slogan:            "slogan",
	Title:             "title",
	LogoId:            "logo_id",
	CreatedBy:         "created_by",
}

// NewCompanyTeamDao creates and returns a new DAO object for table data access.
func NewCompanyTeamDao(proxy ...dao_interface.IDao) *CompanyTeamDao {
	var dao *CompanyTeamDao
	if len(proxy) > 0 {
		dao = &CompanyTeamDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     companyTeamColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &CompanyTeamDao{
		group:   "default",
		table:   "co_company_team",
		columns: companyTeamColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CompanyTeamDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CompanyTeamDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *CompanyTeamDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *CompanyTeamDao) Columns() CompanyTeamColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CompanyTeamDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *CompanyTeamDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CompanyTeamDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *CompanyTeamDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *CompanyTeamDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *CompanyTeamDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *CompanyTeamDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
