// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CompanyTeamDao is the data access object for table pro_company_team.
type CompanyTeamDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns CompanyTeamColumns // columns contains all the column names of Table for convenient usage.
}

// CompanyTeamColumns defines and stores column names for table pro_company_team.
type CompanyTeamColumns struct {
	Id                string //
	Name              string // 团队名称，公司维度下唯一
	OwnerEmployeeId   string // 团队所有者/业务总监/业务经理/团队队长
	CaptainEmployeeId string // 团队队长编号/小组组长
	UnionMainId       string // 所属主体单位ID
	ParentId          string // 父级ID
	Remark            string // 备注
	CreatedAt         string //
	UpdatedAt         string //
	DeletedAt         string //
}

// companyTeamColumns holds the columns for table pro_company_team.
var companyTeamColumns = CompanyTeamColumns{
	Id:                "id",
	Name:              "name",
	OwnerEmployeeId:   "owner_employee_id",
	CaptainEmployeeId: "captain_employee_id",
	UnionMainId:       "union_main_id",
	ParentId:          "parent_id",
	Remark:            "remark",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
}

// NewCompanyTeamDao creates and returns a new DAO object for table data access.
func NewCompanyTeamDao() *CompanyTeamDao {
	return &CompanyTeamDao{
		group:   "default",
		table:   "pro_company_team",
		columns: companyTeamColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CompanyTeamDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CompanyTeamDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CompanyTeamDao) Columns() CompanyTeamColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CompanyTeamDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CompanyTeamDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CompanyTeamDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
