// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CompanyEmployeeDao is the data access object for table pro_company_employee.
type CompanyEmployeeDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns CompanyEmployeeColumns // columns contains all the column names of Table for convenient usage.
}

// CompanyEmployeeColumns defines and stores column names for table pro_company_employee.
type CompanyEmployeeColumns struct {
	Id           string // ID，保持与USERID一致
	No           string // 工号
	Avatar       string // 头像
	Name         string // 姓名
	Mobile       string // 手机号
	UnionMainId  string // 所属主体
	State        string // 状态： -1已离职，0待确认，1已入职
	LastActiveIp string // 最后活跃IP
	HiredAt      string // 入职时间
	CreatedBy    string //
	CreatedAt    string //
	UpdatedBy    string //
	UpdatedAt    string //
	DeletedBy    string //
	DeletedAt    string //
}

// companyEmployeeColumns holds the columns for table pro_company_employee.
var companyEmployeeColumns = CompanyEmployeeColumns{
	Id:           "id",
	No:           "no",
	Avatar:       "avatar",
	Name:         "name",
	Mobile:       "mobile",
	UnionMainId:  "union_main_id",
	State:        "state",
	LastActiveIp: "last_active_ip",
	HiredAt:      "hired_at",
	CreatedBy:    "created_by",
	CreatedAt:    "created_at",
	UpdatedBy:    "updated_by",
	UpdatedAt:    "updated_at",
	DeletedBy:    "deleted_by",
	DeletedAt:    "deleted_at",
}

// NewCompanyEmployeeDao creates and returns a new DAO object for table data access.
func NewCompanyEmployeeDao() *CompanyEmployeeDao {
	return &CompanyEmployeeDao{
		group:   "default",
		table:   "pro_company_employee",
		columns: companyEmployeeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CompanyEmployeeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CompanyEmployeeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CompanyEmployeeDao) Columns() CompanyEmployeeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CompanyEmployeeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CompanyEmployeeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CompanyEmployeeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
