// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdAccountViewDao is the data access object for table co_fd_account_view.
type FdAccountViewDao struct {
	dao_interface.IDao
	table       string               // table is the underlying table name of the DAO.
	group       string               // group is the database configuration group name of current DAO.
	columns     FdAccountViewColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdAccountViewColumns defines and stores column names for table co_fd_account_view.
type FdAccountViewColumns struct {
	Id                 string //
	Name               string //
	UnionLicenseId     string //
	UnionUserId        string //
	CurrencyCode       string //
	IsEnabled          string //
	LimitState         string //
	PrecisionOfBalance string //
	Balance            string //
	Version            string //
	CreatedAt          string //
	CreatedBy          string //
	UpdatedAt          string //
	UpdatedBy          string //
	DeletedAt          string //
	DeletedBy          string //
	SceneType          string //
	AccountType        string //
	AccountNumber      string //
	UnionMainId        string //
	AllowExceed        string //
	FrozenBlance       string //
	CompanyType        string //
}

// fdAccountViewColumns holds the columns for table co_fd_account_view.
var fdAccountViewColumns = FdAccountViewColumns{
	Id:                 "id",
	Name:               "name",
	UnionLicenseId:     "union_license_id",
	UnionUserId:        "union_user_id",
	CurrencyCode:       "currency_code",
	IsEnabled:          "is_enabled",
	LimitState:         "limit_state",
	PrecisionOfBalance: "precision_of_balance",
	Balance:            "balance",
	Version:            "version",
	CreatedAt:          "created_at",
	CreatedBy:          "created_by",
	UpdatedAt:          "updated_at",
	UpdatedBy:          "updated_by",
	DeletedAt:          "deleted_at",
	DeletedBy:          "deleted_by",
	SceneType:          "scene_type",
	AccountType:        "account_type",
	AccountNumber:      "account_number",
	UnionMainId:        "union_main_id",
	AllowExceed:        "allow_exceed",
	FrozenBlance:       "frozen_blance",
	CompanyType:        "company_type",
}

// NewFdAccountViewDao creates and returns a new DAO object for table data access.
func NewFdAccountViewDao(proxy ...dao_interface.IDao) *FdAccountViewDao {
	var dao *FdAccountViewDao
	if len(proxy) > 0 {
		dao = &FdAccountViewDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdAccountViewColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdAccountViewDao{
		group:   "default",
		table:   "co_fd_account_view",
		columns: fdAccountViewColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdAccountViewDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdAccountViewDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdAccountViewDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdAccountViewDao) Columns() FdAccountViewColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdAccountViewDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdAccountViewDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdAccountViewDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdAccountViewDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdAccountViewDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdAccountViewDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdAccountViewDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
