// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdAccountDao is the data access object for table co_fd_account.
type FdAccountDao struct {
	dao_interface.IDao
	table       string           // table is the underlying table name of the DAO.
	group       string           // group is the database configuration group name of current DAO.
	columns     FdAccountColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdAccountColumns defines and stores column names for table co_fd_account.
type FdAccountColumns struct {
	Id                 string // ID
	Name               string // 账户名称
	UnionLicenseId     string // 关联资质ID，大于0时必须保值与 union_user_id 关联得上
	UnionUserId        string // 关联用户ID
	CurrencyCode       string // 货币代码
	IsEnabled          string // 是否启用：1启用，0禁用
	LimitState         string // 限制状态：0不限制，1限制支出、2限制收入
	PrecisionOfBalance string // 货币单位精度：1:元，10:角，100:分，1000:厘，10000:毫，……
	Balance            string // 当前余额，必须要与账单最后一笔交易余额对应得上
	Version            string // 乐观锁所需数据版本字段
	CreatedAt          string //
	CreatedBy          string //
	UpdatedAt          string //
	UpdatedBy          string //
	DeletedAt          string //
	DeletedBy          string //
	SceneType          string // 场景类型：0不限、1充电佣金收入
	AccountType        string // 账户类型：1系统账户、2银行卡、3支付宝、4微信、5云闪付、6翼支付
	AccountNumber      string // 账户编号，例如银行卡号、支付宝账号、微信账号等对应账户类型的编号
	UnionMainId        string // 关联主体ID，与union_license_id 中的union_main_id 一致
	AllowExceed        string // 是否允许存在负余额: 0禁止、1允许
	FrozenBlance       string // 冻结金额
}

// fdAccountColumns holds the columns for table co_fd_account.
var fdAccountColumns = FdAccountColumns{
	Id:                 "id",
	Name:               "name",
	UnionLicenseId:     "union_license_id",
	UnionUserId:        "union_user_id",
	CurrencyCode:       "currency_code",
	IsEnabled:          "is_enabled",
	LimitState:         "limit_state",
	PrecisionOfBalance: "precision_of_balance",
	Balance:            "balance",
	Version:            "version",
	CreatedAt:          "created_at",
	CreatedBy:          "created_by",
	UpdatedAt:          "updated_at",
	UpdatedBy:          "updated_by",
	DeletedAt:          "deleted_at",
	DeletedBy:          "deleted_by",
	SceneType:          "scene_type",
	AccountType:        "account_type",
	AccountNumber:      "account_number",
	UnionMainId:        "union_main_id",
	AllowExceed:        "allow_exceed",
	FrozenBlance:       "frozen_blance",
}

// NewFdAccountDao creates and returns a new DAO object for table data access.
func NewFdAccountDao(proxy ...dao_interface.IDao) *FdAccountDao {
	var dao *FdAccountDao
	if len(proxy) > 0 {
		dao = &FdAccountDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdAccountColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdAccountDao{
		group:   "default",
		table:   "co_fd_account",
		columns: fdAccountColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdAccountDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdAccountDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdAccountDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdAccountDao) Columns() FdAccountColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdAccountDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdAccountDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdAccountDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdAccountDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdAccountDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdAccountDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdAccountDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
