// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdAccountBillsDao is the data access object for table co_fd_account_bills.
type FdAccountBillsDao struct {
	dao_interface.IDao
	table       string                // table is the underlying table name of the DAO.
	group       string                // group is the database configuration group name of current DAO.
	columns     FdAccountBillsColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdAccountBillsColumns defines and stores column names for table co_fd_account_bills.
type FdAccountBillsColumns struct {
	Id            string // ID
	FromUserId    string // 交易发起方UserID，如果是系统则固定为-1
	ToUserId      string // 交易对象UserID
	FdAccountId   string // 财务账户ID
	BeforeBalance string // 交易前账户余额
	Amount        string // 交易金额
	AfterBalance  string // 交易后账户余额
	UnionOrderId  string // 关联业务订单ID
	InOutType     string // 收支类型：1收入，2支出
	TradeType     string // 交易类型，1转账、2消费、4退款、8佣金、16保证金、32诚意金、64手续费/服务费、128提现、256充值、512营收，8192其它
	TradeAt       string // 交易时间
	Remark        string // 备注信息
	TradeState    string // 交易状态：1待支付、2支付中、4已支付、8取消支付、16交易完成、32退款中、64已退款、128支付超时、256已关闭
	DeletedAt     string //
	CreatedAt     string //
	CreatedBy     string //
	HandlingFee   string // 手续费，当前记录产生的手续费，如果有的话
	ExtJson       string // 扩展数据
}

// fdAccountBillsColumns holds the columns for table co_fd_account_bills.
var fdAccountBillsColumns = FdAccountBillsColumns{
	Id:            "id",
	FromUserId:    "from_user_id",
	ToUserId:      "to_user_id",
	FdAccountId:   "fd_account_id",
	BeforeBalance: "before_balance",
	Amount:        "amount",
	AfterBalance:  "after_balance",
	UnionOrderId:  "union_order_id",
	InOutType:     "in_out_type",
	TradeType:     "trade_type",
	TradeAt:       "trade_at",
	Remark:        "remark",
	TradeState:    "trade_state",
	DeletedAt:     "deleted_at",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	HandlingFee:   "handling_fee",
	ExtJson:       "ext_json",
}

// NewFdAccountBillsDao creates and returns a new DAO object for table data access.
func NewFdAccountBillsDao(proxy ...dao_interface.IDao) *FdAccountBillsDao {
	var dao *FdAccountBillsDao
	if len(proxy) > 0 {
		dao = &FdAccountBillsDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdAccountBillsColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdAccountBillsDao{
		group:   "default",
		table:   "co_fd_account_bills",
		columns: fdAccountBillsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdAccountBillsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdAccountBillsDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdAccountBillsDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdAccountBillsDao) Columns() FdAccountBillsColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdAccountBillsDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdAccountBillsDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdAccountBillsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdAccountBillsDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdAccountBillsDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdAccountBillsDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdAccountBillsDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
