// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdAccountBillsViewDao is the data access object for table co_fd_account_bills_view.
type FdAccountBillsViewDao struct {
	dao_interface.IDao
	table       string                    // table is the underlying table name of the DAO.
	group       string                    // group is the database configuration group name of current DAO.
	columns     FdAccountBillsViewColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdAccountBillsViewColumns defines and stores column names for table co_fd_account_bills_view.
type FdAccountBillsViewColumns struct {
	Id            string //
	FromUserId    string //
	ToUserId      string //
	FdAccountId   string //
	BeforeBalance string //
	Amount        string //
	AfterBalance  string //
	UnionOrderId  string //
	UnionMainId   string //
	InOutType     string //
	TradeType     string //
	TradeAt       string //
	Remark        string //
	TradeState    string //
	HandlingFee   string //
	ExtJson       string //
	DeletedAt     string //
	DeletedBy     string //
	CreatedAt     string //
	CreatedBy     string //
	CompanyType   string //
}

// fdAccountBillsViewColumns holds the columns for table co_fd_account_bills_view.
var fdAccountBillsViewColumns = FdAccountBillsViewColumns{
	Id:            "id",
	FromUserId:    "from_user_id",
	ToUserId:      "to_user_id",
	FdAccountId:   "fd_account_id",
	BeforeBalance: "before_balance",
	Amount:        "amount",
	AfterBalance:  "after_balance",
	UnionOrderId:  "union_order_id",
	UnionMainId:   "union_main_id",
	InOutType:     "in_out_type",
	TradeType:     "trade_type",
	TradeAt:       "trade_at",
	Remark:        "remark",
	TradeState:    "trade_state",
	HandlingFee:   "handling_fee",
	ExtJson:       "ext_json",
	DeletedAt:     "deleted_at",
	DeletedBy:     "deleted_by",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	CompanyType:   "company_type",
}

// NewFdAccountBillsViewDao creates and returns a new DAO object for table data access.
func NewFdAccountBillsViewDao(proxy ...dao_interface.IDao) *FdAccountBillsViewDao {
	var dao *FdAccountBillsViewDao
	if len(proxy) > 0 {
		dao = &FdAccountBillsViewDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdAccountBillsViewColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdAccountBillsViewDao{
		group:   "default",
		table:   "co_fd_account_bills_view",
		columns: fdAccountBillsViewColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdAccountBillsViewDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdAccountBillsViewDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdAccountBillsViewDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdAccountBillsViewDao) Columns() FdAccountBillsViewColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdAccountBillsViewDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdAccountBillsViewDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdAccountBillsViewDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdAccountBillsViewDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdAccountBillsViewDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdAccountBillsViewDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdAccountBillsViewDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
