// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdBankCardDao is the data access object for table co_fd_bank_card.
type FdBankCardDao struct {
	dao_interface.IDao
	table       string            // table is the underlying table name of the DAO.
	group       string            // group is the database configuration group name of current DAO.
	columns     FdBankCardColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdBankCardColumns defines and stores column names for table co_fd_bank_card.
type FdBankCardColumns struct {
	Id            string // ID
	BankName      string // 银行名称
	CardType      string // 银行卡类型：1借记卡，2储蓄卡
	CardNumber    string // 银行卡号
	ExpiredAt     string // 有效期
	HolderName    string // 银行卡开户名
	BankOfAccount string // 开户行
	State         string // 状态：0禁用，1正常
	Remark        string // 备注信息
	UserId        string // 用户id，表示属于谁
	CreatedAt     string //
	CreatedBy     string //
	UpdatedAt     string //
	UpdatedBy     string //
	DeletedAt     string //
	DeletedBy     string //
}

// fdBankCardColumns holds the columns for table co_fd_bank_card.
var fdBankCardColumns = FdBankCardColumns{
	Id:            "id",
	BankName:      "bank_name",
	CardType:      "card_type",
	CardNumber:    "card_number",
	ExpiredAt:     "expired_at",
	HolderName:    "holder_name",
	BankOfAccount: "bank_of_account",
	State:         "state",
	Remark:        "remark",
	UserId:        "user_id",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	UpdatedBy:     "updated_by",
	DeletedAt:     "deleted_at",
	DeletedBy:     "deleted_by",
}

// NewFdBankCardDao creates and returns a new DAO object for table data access.
func NewFdBankCardDao(proxy ...dao_interface.IDao) *FdBankCardDao {
	var dao *FdBankCardDao
	if len(proxy) > 0 {
		dao = &FdBankCardDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdBankCardColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdBankCardDao{
		group:   "default",
		table:   "co_fd_bank_card",
		columns: fdBankCardColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdBankCardDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdBankCardDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdBankCardDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdBankCardDao) Columns() FdBankCardColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdBankCardDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdBankCardDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdBankCardDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdBankCardDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdBankCardDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdBankCardDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdBankCardDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
