// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdInvoiceDao is the data access object for table co_fd_invoice.
type FdInvoiceDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns FdInvoiceColumns // columns contains all the column names of Table for convenient usage.
}

// FdInvoiceColumns defines and stores column names for table co_fd_invoice.
type FdInvoiceColumns struct {
	Id            string //
	Name          string // 发票抬头名称
	TaxId         string // 纳税识别号
	Addr          string // 发票收件地址，限纸质
	Email         string // 发票收件邮箱，限电子发票
	UserId        string // 申请人UserID
	AuditUserId   string // 审核人UserID
	AuditReplyMsg string // 审核回复，仅审核不通过时才有值
	AuditAt       string // 审核时间
	State         string // 状态：0待审核、1已通过、-1不通过
	UnionMainId   string // 主体ID：运营商ID、服务商ID、商户ID、消费者ID
	CreatedAt     string //
	CreatedBy     string //
	UpdatedAt     string //
	UpdatedBy     string //
	DeletedAt     string //
	DeletedBy     string //
}

// fdInvoiceColumns holds the columns for table co_fd_invoice.
var fdInvoiceColumns = FdInvoiceColumns{
	Id:            "id",
	Name:          "name",
	TaxId:         "tax_id",
	Addr:          "addr",
	Email:         "email",
	UserId:        "user_id",
	AuditUserId:   "audit_user_id",
	AuditReplyMsg: "audit_reply_msg",
	AuditAt:       "audit_at",
	State:         "state",
	UnionMainId:   "union_main_id",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	UpdatedBy:     "updated_by",
	DeletedAt:     "deleted_at",
	DeletedBy:     "deleted_by",
}

// NewFdInvoiceDao creates and returns a new DAO object for table data access.
func NewFdInvoiceDao(proxy ...dao_interface.IDao) *FdInvoiceDao {
	var dao *FdInvoiceDao
	if len(proxy) > 0 {
		dao = &FdInvoiceDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: fdInvoiceColumns,
		}
		return dao
	}

	return &FdInvoiceDao{
		group:   "default",
		table:   "co_fd_invoice",
		columns: fdInvoiceColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdInvoiceDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdInvoiceDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdInvoiceDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdInvoiceDao) Columns() FdInvoiceColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdInvoiceDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdInvoiceDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdInvoiceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
