// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdInvoiceDetailViewDao is the data access object for table co_fd_invoice_detail_view.
type FdInvoiceDetailViewDao struct {
	dao_interface.IDao
	table       string                     // table is the underlying table name of the DAO.
	group       string                     // group is the database configuration group name of current DAO.
	columns     FdInvoiceDetailViewColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdInvoiceDetailViewColumns defines and stores column names for table co_fd_invoice_detail_view.
type FdInvoiceDetailViewColumns struct {
	Id            string //
	TaxNumber     string //
	TaxName       string //
	BillIds       string //
	Amount        string //
	Rate          string //
	RateMount     string //
	Remark        string //
	Type          string //
	State         string //
	AuditUserIds  string //
	MakeType      string //
	MakeUserId    string //
	MakeAt        string //
	CourierName   string //
	CourierNumber string //
	FdInvoiceId   string //
	AuditUserId   string //
	AuditReplyMsg string //
	AuditAt       string //
	UserId        string //
	UnionMainId   string //
	Email         string //
	CreatedAt     string //
	CreatedBy     string //
	UpdatedAt     string //
	UpdatedBy     string //
	DeletedAt     string //
	DeletedBy     string //
	BelongTo      string //
	CompanyType   string //
}

// fdInvoiceDetailViewColumns holds the columns for table co_fd_invoice_detail_view.
var fdInvoiceDetailViewColumns = FdInvoiceDetailViewColumns{
	Id:            "id",
	TaxNumber:     "tax_number",
	TaxName:       "tax_name",
	BillIds:       "bill_ids",
	Amount:        "amount",
	Rate:          "rate",
	RateMount:     "rate_mount",
	Remark:        "remark",
	Type:          "type",
	State:         "state",
	AuditUserIds:  "audit_user_ids",
	MakeType:      "make_type",
	MakeUserId:    "make_user_id",
	MakeAt:        "make_at",
	CourierName:   "courier_name",
	CourierNumber: "courier_number",
	FdInvoiceId:   "fd_invoice_id",
	AuditUserId:   "audit_user_id",
	AuditReplyMsg: "audit_reply_msg",
	AuditAt:       "audit_at",
	UserId:        "user_id",
	UnionMainId:   "union_main_id",
	Email:         "email",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	UpdatedBy:     "updated_by",
	DeletedAt:     "deleted_at",
	DeletedBy:     "deleted_by",
	BelongTo:      "belong_to",
	CompanyType:   "company_type",
}

// NewFdInvoiceDetailViewDao creates and returns a new DAO object for table data access.
func NewFdInvoiceDetailViewDao(proxy ...dao_interface.IDao) *FdInvoiceDetailViewDao {
	var dao *FdInvoiceDetailViewDao
	if len(proxy) > 0 {
		dao = &FdInvoiceDetailViewDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdInvoiceDetailViewColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdInvoiceDetailViewDao{
		group:   "default",
		table:   "co_fd_invoice_detail_view",
		columns: fdInvoiceDetailViewColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdInvoiceDetailViewDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdInvoiceDetailViewDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdInvoiceDetailViewDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdInvoiceDetailViewDao) Columns() FdInvoiceDetailViewColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdInvoiceDetailViewDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdInvoiceDetailViewDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdInvoiceDetailViewDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdInvoiceDetailViewDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdInvoiceDetailViewDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdInvoiceDetailViewDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdInvoiceDetailViewDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
