// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdInvoiceViewDao is the data access object for table co_fd_invoice_view.
type FdInvoiceViewDao struct {
	dao_interface.IDao
	table       string               // table is the underlying table name of the DAO.
	group       string               // group is the database configuration group name of current DAO.
	columns     FdInvoiceViewColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// FdInvoiceViewColumns defines and stores column names for table co_fd_invoice_view.
type FdInvoiceViewColumns struct {
	Id            string //
	Name          string //
	TaxId         string //
	Addr          string //
	Email         string //
	UserId        string //
	AuditUserId   string //
	AuditReplyMsg string //
	AuditAt       string //
	State         string //
	UnionMainId   string //
	CreatedAt     string //
	CreatedBy     string //
	UpdatedAt     string //
	UpdatedBy     string //
	DeletedAt     string //
	DeletedBy     string //
	CompanyType   string //
}

// fdInvoiceViewColumns holds the columns for table co_fd_invoice_view.
var fdInvoiceViewColumns = FdInvoiceViewColumns{
	Id:            "id",
	Name:          "name",
	TaxId:         "tax_id",
	Addr:          "addr",
	Email:         "email",
	UserId:        "user_id",
	AuditUserId:   "audit_user_id",
	AuditReplyMsg: "audit_reply_msg",
	AuditAt:       "audit_at",
	State:         "state",
	UnionMainId:   "union_main_id",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	UpdatedBy:     "updated_by",
	DeletedAt:     "deleted_at",
	DeletedBy:     "deleted_by",
	CompanyType:   "company_type",
}

// NewFdInvoiceViewDao creates and returns a new DAO object for table data access.
func NewFdInvoiceViewDao(proxy ...dao_interface.IDao) *FdInvoiceViewDao {
	var dao *FdInvoiceViewDao
	if len(proxy) > 0 {
		dao = &FdInvoiceViewDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     fdInvoiceViewColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &FdInvoiceViewDao{
		group:   "default",
		table:   "co_fd_invoice_view",
		columns: fdInvoiceViewColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdInvoiceViewDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdInvoiceViewDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *FdInvoiceViewDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *FdInvoiceViewDao) Columns() FdInvoiceViewColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdInvoiceViewDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *FdInvoiceViewDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdInvoiceViewDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *FdInvoiceViewDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *FdInvoiceViewDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *FdInvoiceViewDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *FdInvoiceViewDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
